# access httpd pod(s) (having the label app=service-test) by
# `curl <node-ip>:30008`
apiVersion: v1
kind: Service
metadata:
  name: node-port-test
spec:
  type: NodePort
  ports:
      # `targetPort` is optional and falls back to `port`
    - targetPort: 80
      port: 80
      # sth between 30000 and 32767
      # `nodePort` is optional and falls back to random port
      nodePort: 30008
  selector:
    app: service-test