# without a service there's no way to access the pod from outside
# `kubectl logs simple-mongo-pod` will show that the pod was started alright
apiVersion: v1
kind: Pod
metadata:
  name: simple-mongo-pod
  labels:
    app: simple-mongo-test
    type: mongodb
spec:
  containers:
    - name: mongo-container
      image: mongo
      command:
        - mongod